### ISSUE TITLE
Add a task runner

### ISSUE THREAD

**Issue by vaibhav111tandon** [vaibhav111tandon/vov.css#10]
So that it automatically minifies the css generated.

**Comment by vitebo** [comment]
I can work on it

**Comment by vaibhav111tandon** [comment]
yeah, sure

**Comment by vitebo** [comment]
i hope this helps you
https://github.com/vaibhav111tandon/vov.css/pull/11

**Comment by Techcatchers** [comment]
Created a PR fixing this issue #12
