### ISSUE TITLE
Add more classes for animations

### ISSUE THREAD

**Issue by vaibhav111tandon** [vaibhav111tandon/vov.css#3]

**Comment by alvaromontoro** [comment]
Any specific browser support needed?

**Comment by vaibhav111tandon** [comment]
For the mean time just add the animation without any particular browser prefix.

**Comment by alvaromontoro** [comment]
Wow! That was a quick reply :)
I was thinking about submitting a swivel animation if that's ok.

**Comment by vaibhav111tandon** [comment]
Yeah, sure👍
