### ISSUE TITLE
NPM & Packagist

### ISSUE THREAD

**Issue by trymeouteh** [vaibhav111tandon/vov.css#30]
Please add this package onto NPM and Packagist for easy installation in our projects!

**Comment by vaibhav111tandon** [comment]
@trymeouteh Thanks for reaching out, will deploy this to NPM

**Comment by trymeouteh** [comment]
And please also deploy this on Packagist for those who want this in there PHP websites. Packagist is a Composer package repository.

https://packagist.org/
https://getcomposer.org/

**Comment by vaibhav111tandon** [comment]
Hey @trymeouteh, currently I am not trying to maintain this for PHP, can you please try using some bridge service(if any) to make it work for PHP or load it on the client end?
Though, for NPM, you can refer this: https://www.npmjs.com/package/vov.css
