### ISSUE TITLE
Run animation when in viewport

### ISSUE THREAD

**Issue by chimok** [vaibhav111tandon/vov.css#34]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to use the css classes when I scroll in a viewport. For that i wrote a simple javascript function using IntersectionObserver on all elements with CSS class `if-viewport`. If the intersectionobserver has a match it adds the css class `in-viewport`. This logic works totally well & stable

But the problem is the initial state on a element! If i scroll from the right side, the initial state should be "place element on right side". When i fade in, initial state should be transparent....

What happens currently: The user see the image.... then it disappear .....then the animation starts.

Is it possible to get it done with vov or any ideas?

**Comment by vaibhav111tandon** [comment]
Hey @chimok sorry for the late reply.
are you referring to add any css class which will solve the issue you are facing?

**Comment by chimok** [comment]
Hello @vaibhav111tandon, I add my code to #8 so we could close this because the question is how to use this with javascript.
