### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by vaibhav111tandon** [vaibhav111tandon/vov.css#9]
- Show animations in a better and simple way.
- More information should be provided in a website.

**Comment by JoelLau** [comment]
@vaibhav111tandon I like what you've done with this repository and the website so far

**Comment by JoelLau** [comment]
I have a couple of questions for you regarding what changes you'd like to see here:

- which parts of the current controls don't you like ?
- what kinds of information do you think will be helpful ?

**Comment by vaibhav111tandon** [comment]
- Select tag is not working properly on different screens.
- A download button for downloading the library.
- Background color changing animation is not looking good.
These are some of the changes I think should be done.
And your further changes are most welcomed :)

**Comment by vaibhav111tandon** [comment]
Background Colour and the select tag issue has been fixed
